# Generated by Django 4.2.15 on 2024-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_total_order_product_shop_id_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_shop_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_shop_id',
            field=models.ManyToManyField(to='products.product_shop'),
        ),
    ]
