# Generated by Django 4.2.15 on 2024-09-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_shop_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total',
            new_name='cartTotal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='numItemsInCart',
        ),
    ]
